// Tiny driver: load three JSON inputs from an examples/<event>/ directory,
// run generateSequence(), write final_sequence.md.
//
// Usage (from repo root):
//   GEMINI_API_KEY=... npx tsx scripts/run-example.ts examples/rsa-conference-2026
//
// If sequencer-output.json already exists in the example dir, the LLM step is
// skipped and only the markdown rendering re-runs (saves ~5 min). Pass
// `--rerun` to force regeneration.

import { existsSync } from 'node:fs';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { generateSequence } from '../src/agents/sequencer.js';
import type {
  EventContext,
  CompanyICP,
  SequenceParams,
  SequencerOutput,
  OutreachSequence,
  OutreachTouch,
} from '../src/types/index.js';

async function readJson<T>(dir: string, file: string): Promise<T> {
  const raw = await readFile(join(dir, file), 'utf-8');
  return JSON.parse(raw) as T;
}

function offsetLabel(days: number): string {
  if (days === 0) return 'T0';
  if (days < 0) return `T${days}d`;
  return `T+${days}d`;
}

function renderTouchMarkdown(touch: OutreachTouch, n: number): string {
  const subjectLine =
    touch.channel === 'email'
      ? `_Subject:_ \`${touch.subject || '(none)'}\``
      : '_Subject:_ (none)';
  const meta = [
    `\`channel: ${touch.channel}\``,
    `\`offset: ${offsetLabel(touch.send_at_offset_days)}\``,
    `\`type: ${touch.touch_type}\``,
    `\`cta: ${touch.cta_type}\``,
    `\`words: ${touch.word_count}\``,
  ];
  if (touch.quality_flag === 'rules_violated') {
    meta.push('`validation: rules_violated`');
  }
  return [
    `### Touch ${n}: ${offsetLabel(touch.send_at_offset_days)} · ${touch.touch_type}`,
    '',
    subjectLine,
    '',
    `> ${touch.body.replace(/\n/g, '\n> ')}`,
    '',
    meta.join(' · '),
  ].join('\n');
}

function renderSequenceMarkdown(
  eventContext: EventContext,
  companyIcp: CompanyICP,
  params: SequenceParams,
  sequencesByPersona: { [personaId: string]: OutreachSequence },
): string {
  const lines: string[] = [];
  lines.push(`# Outbound Sequence: ${eventContext.name}`);
  lines.push('');
  lines.push(
    `**Event:** ${eventContext.name} · ${eventContext.dates} · ${eventContext.location}`,
  );
  lines.push(`**Industry:** ${companyIcp.industry}`);
  lines.push(`**Company size:** ${companyIcp.sizeRange}`);
  lines.push(
    `**Lead time:** ${params.leadTimeWeeks} weeks · **Channels:** ${params.channels.join(' + ')}`,
  );
  lines.push(
    `**Sender:** ${params.sendingIdentity.name}, ${params.sendingIdentity.title} at ${params.sendingIdentity.company}`,
  );
  lines.push('');
  lines.push(
    '> Generated by `event-outbound-skill` — every touch validated against `data/cold-email-benchmarks.json` (subject ≤4 words lowercase, body 50–100 words and 3–4 sentences, banned-phrase blocklist, "you" > "we" pronoun majority, CTA ranking `make_offer` > `ask_for_interest`, no exclamation marks, no em-dashes). Touches that fail all 3 generation attempts ship with `quality_flag: rules_violated` so a human can reroute them rather than ship bad copy.',
  );
  lines.push('');
  lines.push('---');
  lines.push('');
  for (const persona of companyIcp.personas) {
    const seq = sequencesByPersona[persona.personaId];
    if (!seq) continue;
    lines.push(`## Persona: ${persona.role}`);
    lines.push('');
    lines.push(`**Priorities** · ${persona.priorities.join(' · ')}`);
    lines.push('');
    lines.push(`**Pain points** · ${persona.painPoints.join(' · ')}`);
    lines.push('');
    seq.touches.forEach((t, i) => {
      lines.push(renderTouchMarkdown(t, i + 1));
      lines.push('');
      lines.push('---');
      lines.push('');
    });
  }
  return lines.join('\n');
}

async function main() {
  const args = process.argv.slice(2);
  const exampleDir = args.find((a) => !a.startsWith('--'));
  const forceRerun = args.includes('--rerun');
  if (!exampleDir) {
    console.error('Usage: tsx scripts/run-example.ts <example-dir> [--rerun]');
    process.exit(1);
  }

  const eventContext = await readJson<EventContext>(exampleDir, 'event-context.json');
  const companyIcp = await readJson<CompanyICP>(exampleDir, 'company-icp.json');
  const sequenceParams = await readJson<SequenceParams>(exampleDir, 'sequence-params.json');

  const jsonPath = join(exampleDir, 'sequencer-output.json');

  let out: SequencerOutput;
  if (!forceRerun && existsSync(jsonPath)) {
    console.error(`Reusing cached ${jsonPath} (pass --rerun to regenerate).`);
    out = await readJson<SequencerOutput>(exampleDir, 'sequencer-output.json');
  } else {
    console.error(
      `Generating ${companyIcp.personas.length} persona sequences for ${eventContext.name} ...`,
    );
    const start = Date.now();
    out = await generateSequence(eventContext, companyIcp, sequenceParams);
    const elapsed = ((Date.now() - start) / 1000).toFixed(1);
    console.error(`Generation complete in ${elapsed}s.`);
    await writeFile(jsonPath, JSON.stringify(out, null, 2), 'utf-8');
    console.error(`Wrote ${jsonPath}`);
  }

  // Validation summary
  let total = 0;
  let flagged = 0;
  for (const personaId of Object.keys(out.sequencesByPersona)) {
    for (const t of out.sequencesByPersona[personaId].touches) {
      total += 1;
      if (t.quality_flag === 'rules_violated') flagged += 1;
    }
  }
  console.error(`Touches: ${total} total, ${flagged} flagged rules_violated`);

  const md = renderSequenceMarkdown(
    eventContext,
    companyIcp,
    sequenceParams,
    out.sequencesByPersona,
  );
  const mdPath = join(exampleDir, 'final_sequence.md');
  await writeFile(mdPath, md, 'utf-8');
  console.error(`Wrote ${mdPath}`);
}

main().catch((e) => {
  console.error('Sequencer driver failed:', e);
  process.exit(1);
});
